apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/qwan1-tenant/myapp/devfile-sample-python-basic@sha256:f202fcf380de532e04a4babd2148e60a3a0ed75fbd93b3025f1853d2f0dcda9d
        name: my-python
        resources: {}
status: {}
