apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: appstudio-devfile-sample-python-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: appstudio-devfile-sample-python-basic
    app.kubernetes.io/part-of: myapp
  name: appstudio-devfile-sample-python-basic
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: appstudio-devfile-sample-python-basic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: appstudio-devfile-sample-python-basic
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/qwan1-tenant/myapp/appstudio-devfile-sample-python-basic@sha256:5b7f1a7138ae1d9628408218a89359251a98e201d964179090ba3cf327699b7e
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
